services:
  app:
    build:
      context: ./nextjs
    environment:
      NODE_ENV: production
    volumes:
      - app_data:/nextjs
    networks: 
      - docker-compose-network     
    ports:
      - 3000:3000
    restart: always 
  
  node_red:
    image: nodered/node-red:3.1-debian
    volumes:
      - ${PWD}/node-red:/node-red    
    networks: 
      - docker-compose-network     
    ports:
      - 1880:1880
    restart: always

  data:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ${PWD}/mongodb:/data/db
    networks: 
      - docker-compose-network
    ports:
      - 27017:27017
    restart: always    

volumes:
  app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/nextjs

networks: 
    docker-compose-network:
      driver: bridge
