import styles from "./loja.module.css"
import Link from "next/link";
import ProductCard from "@/app/components/ProductCard/ProductCard";

export default function Loja() {
    const product = {
        image:"/assets/celular.jpeg",
        name:"Product",
        description: "Generated by create next app",
        price: 9999,
    }

    return (
        <div>
            <header className={styles.header}>
                <nav className={styles.nav}>
                    <ul className={styles.ul}>
                        <li className={styles.li}>
                            <Link className={styles.link} href="#">Home</Link>
                            <Link className={styles.link} href="#">Loja</Link>
                            <Link className={styles.link} href="#">Livros</Link>
                            <Link className={styles.link} href="#">Eletrônicos</Link>
                            <Link className={styles.link} href="#">Presentes</Link>
                        </li>
                    </ul>
                </nav>
            </header>
            <main>
                <ProductCard product={product}></ProductCard>
            </main>
            <footer className={styles.footer}>
                <p className={styles.p}>&copy; 2024 All rights reserved.</p>
            </footer>
        </div>

    )
}